# Panda is a core library for Data Manupilation & Analysis

## Series - One Dimensional

In [1]:
import pandas as pd

In [3]:
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s1

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [4]:
type(s1)

pandas.core.series.Series

In [7]:
# Changing Index from 0 to 'a' Numbers to Alphabets

s2 = pd.Series([1,2,3,4,5],index=["a","b","c","d","e"])
s2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
# Creating Series Object from Dicitionary
d1 = ({ "omkar":27,"dipesh":89,"ratanlal":45
})

In [11]:
d1

{'omkar': 27, 'dipesh': 89, 'ratanlal': 45}

In [12]:
pd.Series(d1)

omkar       27
dipesh      89
ratanlal    45
dtype: int64

In [13]:
# Changing index Position
s2 = pd.Series([1,2,3,4,5],index=["e","b","d","c","a"])
s2

e    1
b    2
d    3
c    4
a    5
dtype: int64

In [19]:
# Extracting Individual Elelment from Series
s = pd.Series([1,2,3,4,5])
s[:-1]

0    1
1    2
2    3
3    4
dtype: int64

In [20]:
# Adding Scalar value to Series and Adding to Series
s+3

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [22]:
s+s1

0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64

## DataFrame - Multi Dimensional

In [23]:
#Creating DataFrame
d1 = pd.DataFrame({"Name": ["omkar","Dipesh","Ratanlal"],"Marks":[12,2,3]})

In [24]:
d1

       Name  Marks
0     omkar     12
1    Dipesh      2
2  Ratanlal      3

In [25]:
type(d1)

pandas.core.frame.DataFrame

In [26]:
d1.head()

       Name  Marks
0     omkar     12
1    Dipesh      2
2  Ratanlal      3

In [27]:
d1.tail()

       Name  Marks
0     omkar     12
1    Dipesh      2
2  Ratanlal      3

In [28]:
# Reading DataFrame
Iris=pd.read_csv("Iris.csv")

In [29]:
Iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [31]:
Iris.head(2)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa

In [33]:
Iris.tail(2)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [35]:
Iris.shape

(150, 6)

In [37]:
Iris.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [39]:
Iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

# .loc & .iloc Method

# iloc Index Location
Iris.iloc[Row,col]

In [42]:
Iris.iloc[0:8,0:10]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa

## Iris.loc from specific Series to Specific Series

In [58]:
Iris.loc[0:5,("SepalLengthCm","Species")] # 0:5 Number of Rows

   SepalLengthCm      Species
0            5.1  Iris-setosa
1            4.9  Iris-setosa
2            4.7  Iris-setosa
3            4.6  Iris-setosa
4            5.0  Iris-setosa
5            5.4  Iris-setosa

# Droping a Particular Column

In [64]:
Iris.drop('PetalLengthCm',axis=1) # axis=1 Droping Column & axis=0 Drpoing Row

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
4      5            5.0           3.6           0.2     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[150 rows x 5 columns]

#  Droping a Particular Row

In [65]:
Iris.drop([1,2,3,4,5,6,7,8],axis=0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
10,11,5.4,3.7,1.5,0.2,Iris-setosa
11,12,4.8,3.4,1.6,0.2,Iris-setosa
12,13,4.8,3.0,1.4,0.1,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

# More Pandas Function

In [66]:
Iris.mean()

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [67]:
Iris.std()

Id               43.445368
SepalLengthCm     0.828066
SepalWidthCm      0.433594
PetalLengthCm     1.764420
PetalWidthCm      0.763161
dtype: float64

In [68]:
Iris.median()

Id               75.50
SepalLengthCm     5.80
SepalWidthCm      3.00
PetalLengthCm     4.35
PetalWidthCm      1.30
dtype: float64

In [69]:
Iris.max()

Id                          150
SepalLengthCm               7.9
SepalWidthCm                4.4
PetalLengthCm               6.9
PetalWidthCm                2.5
Species          Iris-virginica
dtype: object

In [70]:
Iris.min()

Id                         1
SepalLengthCm            4.3
SepalWidthCm               2
PetalLengthCm              1
PetalWidthCm             0.1
Species          Iris-setosa
dtype: object